object Java: TJava
  Left = 0
  Top = 0
  AutoSize = True
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'Java'
  ClientHeight = 25
  ClientWidth = 75
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
